const request = require('supertest');
const app = require('../src/app');
const supabase = require('../src/config/db'); // Direct DB access for verification
require('dotenv').config();

// Increase timeout for slow network
jest.setTimeout(60000);

describe('Voting System Exhaustive Tests', () => {

    // --- VARIABLES TO STORE DATA BETWEEN TESTS ---
    let adminToken = '';
    let voterToken = '';
    let voterId = '';

    // Poll 1: Standard Public Poll
    let standardPollId = '';
    let standardOption1 = '';
    let standardOption2 = '';

    // Poll 2: Anonymous Poll
    let anonPollId = '';
    let anonOption1 = '';

    // Poll 3: Closed Poll
    let closedPollId = '';
    let closedOption1 = '';

    // Poll 4: Guest Poll (For IP Testing)
    let guestPollId = '';
    let guestOption1 = '';

    const adminEmail = `admin_vote_${Date.now()}@test.com`;
    const voterEmail = `voter_vote_${Date.now()}@test.com`;

    // ---------------------------------------------------------
    // 1. SETUP: Create Users and Polls
    // ---------------------------------------------------------
    beforeAll(async () => {
        // A. Register Admin
        const resAdmin = await request(app).post('/api/auth/register').send({
            name: 'Admin', email: adminEmail, password: '123', role: 'ADMIN'
        });
        adminToken = resAdmin.body.token;

        // B. Register Voter
        const resVoter = await request(app).post('/api/auth/register').send({
            name: 'Voter', email: voterEmail, password: '123', role: 'VOTER'
        });
        voterToken = resVoter.body.token;
        voterId = resVoter.body.user.id;

        // C. Create STANDARD Poll
        const poll1 = await request(app).post('/api/polls')
            .set('Authorization', `Bearer ${adminToken}`)
            .send({
                title: "Standard Poll", options: ["Cat", "Dog"],
                settings: { isAnonymous: false, status: "ACTIVE" }
            });
        standardPollId = poll1.body.poll.id;
        // We need to fetch the poll to get Option IDs (since they are generated by DB)
        const getPoll1 = await request(app).get(`/api/polls/${standardPollId}`);
        standardOption1 = getPoll1.body.poll_options[0].id;
        standardOption2 = getPoll1.body.poll_options[1].id;

        // D. Create ANONYMOUS Poll
        const poll2 = await request(app).post('/api/polls')
            .set('Authorization', `Bearer ${adminToken}`)
            .send({
                title: "Secret Poll", options: ["Secret A", "Secret B"],
                settings: { isAnonymous: true }
            });
        anonPollId = poll2.body.poll.id;
        const getPoll2 = await request(app).get(`/api/polls/${anonPollId}`);
        anonOption1 = getPoll2.body.poll_options[0].id;

        // E. Create CLOSED Poll
        const poll3 = await request(app).post('/api/polls')
            .set('Authorization', `Bearer ${adminToken}`)
            .send({ title: "Closed Poll", options: ["X", "Y"] });
        closedPollId = poll3.body.poll.id;
        const getPoll3 = await request(app).get(`/api/polls/${closedPollId}`);
        closedOption1 = getPoll3.body.poll_options[0].id;

        // Manual DB Hack to close the poll
        await supabase.from('polls').update({ status: 'CLOSED' }).eq('id', closedPollId);

        // F. Create GUEST Poll (New addition for IP testing)
        const poll4 = await request(app).post('/api/polls')
            .set('Authorization', `Bearer ${adminToken}`)
            .send({ title: "Guest Poll", options: ["G1", "G2"] });
        guestPollId = poll4.body.poll.id;
        const getPoll4 = await request(app).get(`/api/polls/${guestPollId}`);
        guestOption1 = getPoll4.body.poll_options[0].id;
    });

    // ---------------------------------------------------------
    // 2. VALIDATION TESTS (Bad Inputs)
    // ---------------------------------------------------------

    it('Should fail if Poll ID does not exist', async () => {
        const res = await request(app)
            .post(`/api/polls/999999/vote`)
            .send({ optionId: 123 });

        expect(res.statusCode).toEqual(404);
    });

    it('Should fail if Option ID is missing', async () => {
        const res = await request(app)
            .post(`/api/polls/${standardPollId}/vote`)
            .send({}); // Empty body

        expect(res.statusCode).toEqual(400);
        expect(res.body.message).toMatch(/required/);
    });

    it('Should FAIL if Option ID does not belong to the Poll (Cross-Poll Attack)', async () => {
        // Trying to use an Option from Poll 1 on Poll 2
        const res = await request(app)
            .post(`/api/polls/${anonPollId}/vote`)
            .set('Authorization', `Bearer ${voterToken}`)
            .send({ optionId: standardOption1 });

        expect(res.statusCode).toEqual(400);
        expect(res.body.message).toMatch(/does not belong/i);
    });

    it('Should FAIL if Poll is CLOSED', async () => {
        const res = await request(app)
            .post(`/api/polls/${closedPollId}/vote`)
            .set('Authorization', `Bearer ${voterToken}`)
            .send({ optionId: closedOption1 });

        expect(res.statusCode).toEqual(400);
        expect(res.body.message).toMatch(/closed/i);
    });

    // ---------------------------------------------------------
    // 3. LOGIC TESTS (Voting & Counts)
    // ---------------------------------------------------------

    it('Should allow a Logged-In User to Vote', async () => {
        const res = await request(app)
            .post(`/api/polls/${standardPollId}/vote`)
            .set('Authorization', `Bearer ${voterToken}`)
            .send({ optionId: standardOption1 });

        expect(res.statusCode).toEqual(201);
        expect(res.body.message).toMatch(/success/);
    });

    it('Should PREVENT the same User from voting again (Double Vote)', async () => {
        const res = await request(app)
            .post(`/api/polls/${standardPollId}/vote`)
            .set('Authorization', `Bearer ${voterToken}`)
            .send({ optionId: standardOption2 });

        expect(res.statusCode).toEqual(403);
        expect(res.body.message).toMatch(/already voted/i);
    });

    it('Should verify the Vote Count increased in DB', async () => {
        const res = await request(app).get(`/api/polls/${standardPollId}`);

        // Find the option we voted for
        const votedOption = res.body.poll_options.find(o => o.id === standardOption1);

        // Should be 1 (User vote)
        expect(votedOption.vote_count_cache).toBeGreaterThanOrEqual(1);
    });

    // ---------------------------------------------------------
    // 4. GUEST / IP VOTING TESTS
    // ---------------------------------------------------------

    it('Should allow a Guest (No Token) to Vote', async () => {
        const res = await request(app)
            .post(`/api/polls/${guestPollId}/vote`) // <--- USING GUEST POLL
            .send({ optionId: guestOption1 });

        expect(res.statusCode).toEqual(201);
    });

    it('Should PREVENT the same Guest IP from voting again', async () => {
        const res = await request(app)
            .post(`/api/polls/${guestPollId}/vote`) // <--- USING GUEST POLL
            .send({ optionId: guestOption1 });

        expect(res.statusCode).toEqual(403);
        expect(res.body.message).toMatch(/already voted/i);
    });

    // ---------------------------------------------------------
    // 5. ANONYMITY TESTS
    // ---------------------------------------------------------

    it('Should not save User ID for Anonymous Polls', async () => {
        // 1. Vote as logged in user on Anonymous Poll
        const res = await request(app)
            .post(`/api/polls/${anonPollId}/vote`)
            .set('Authorization', `Bearer ${voterToken}`)
            .send({ optionId: anonOption1 });

        expect(res.statusCode).toEqual(201);

        // 2. Direct DB Check: Find the vote row
        const { data: voteRow } = await supabase
            .from('votes')
            .select('*')
            .eq('poll_id', anonPollId)
            .single();

        // 3. Verify
        expect(voteRow).toBeDefined();
        expect(voteRow.user_id).toBeNull(); // <--- CRITICAL: Must be null
        expect(voteRow.ip_address_hash).toBeDefined();
    });

});